import { toMoneyString, toQuantityString } from '../../utils/decimal';
import type { OrderDto, OrderWithRelations } from './order.types';

export function toOrderDto(order: OrderWithRelations): OrderDto {
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    restaurantId: order.restaurantId,
    restaurantName: order.restaurant?.restaurantName ?? null,
    assignedVendorId: order.assignedVendorId,
    assignedVendorName: order.assignedVendor?.vendorName ?? null,
    status: order.status,
    currency: order.currency,
    subtotal: toMoneyString(order.subtotal),
    discountAmount: toMoneyString(order.discountAmount),
    gstAmount: toMoneyString(order.gstAmount),
    deliveryCharges: toMoneyString(order.deliveryCharges),
    totalAmount: toMoneyString(order.totalAmount),
    advancePercent: order.advancePercent.toFixed(2),
    advanceAmount: toMoneyString(order.advanceAmount),
    remainingAmount: toMoneyString(order.remainingAmount),
    placedAt: order.placedAt?.toISOString() ?? null,
    paymentSubmittedAt: order.paymentSubmittedAt?.toISOString() ?? null,
    paymentVerifiedAt: order.paymentVerifiedAt?.toISOString() ?? null,
    reviewedAt: order.reviewedAt?.toISOString() ?? null,
    assignedAt: order.assignedAt?.toISOString() ?? null,
    acceptedAt: order.acceptedAt?.toISOString() ?? null,
    readyAt: order.readyAt?.toISOString() ?? null,
    deliveredAt: order.deliveredAt?.toISOString() ?? null,
    completedAt: order.completedAt?.toISOString() ?? null,
    rejectedAt: order.rejectedAt?.toISOString() ?? null,
    cancelledAt: order.cancelledAt?.toISOString() ?? null,
    items: order.items.map((item) => ({
      id: item.id,
      productId: item.productId,
      productName: item.productName,
      sku: item.sku,
      unit: item.unit,
      unitPrice: toMoneyString(item.unitPrice),
      quantity: toQuantityString(item.quantity),
      subtotal: toMoneyString(item.subtotal),
    })),
    statusHistory: order.statusHistory.map((history) => ({
      id: history.id,
      oldStatus: history.oldStatus,
      newStatus: history.newStatus,
      changedBy: history.changedBy,
      remarks: history.remarks,
      createdAt: history.createdAt.toISOString(),
    })),
    payments: order.payments.map((payment) => ({
      id: payment.id,
      paymentType: payment.paymentType,
      amount: toMoneyString(payment.amount),
      currency: payment.currency,
      status: payment.status,
      proofUrl: payment.proofUrl,
      transactionReference: payment.transactionReference,
      remarks: payment.remarks,
      verifiedAt: payment.verifiedAt?.toISOString() ?? null,
      createdAt: payment.createdAt.toISOString(),
    })),
    createdAt: order.createdAt.toISOString(),
    updatedAt: order.updatedAt.toISOString(),
  };
}
